### PR TITLE
Fixes #1 - Allow code to build for Swift compilers <5.5

### LINKED ISSUE #1: Swift compiler <5.5 has compile failure in Float+Test.swift
All testing was done on 13" M1 MBP running macOS 11.5.2
 
Local testing done with:
- Xcode 13.0 (release version); Swift 5.5
- Xcode 12.5.1 (last released version); Swift 5.4.2
 
 - Devices: 
M1 13" MBP 

## Describe the bug
Build error on lines 22, 67, 72 of Tes+Floats.swift when compiling with Swift 5.4.2 (Xcode 12.5.1)

## Steps to reproduce
1) sudo xcode-select -s /Applications/Xcode-12.5.1.app/Contents/Developer/
2) cd [directory for package]
3) swift test

## Expected behavior
Builds and all tests pass.

## Stack trace, compiler error, code 

```
> Logging % swift test
> /Users/Shared/OpenSource/Logging/Tests/LoggingTests/Test+Floats.swift:22:24: error: no exact matches in call to instance method 'appendInterpolation'
>         logger.debug("\(value, format: .fixed(precision: 2), privacy: .public)")
>                        ^
> /Users/Shared/OpenSource/Logging/Sources/Logging/Interpolation.swift:67:26: note: candidate expects value of type 'Float' for parameter #1
>     public mutating func appendInterpolation(_ number: @autoclosure @escaping () -> Float, format: LogFloatFormatting = .fixed, align: LogStringAlignment = .none, privacy: LogPrivacy = .private) {
>                          ^
> /Users/Shared/OpenSource/Logging/Sources/Logging/Interpolation.swift:72:26: note: candidate expects value of type 'Double' for parameter #1
>     public mutating func appendInterpolation(_ number: @autoclosure @escaping () -> Double, format: LogFloatFormatting = .fixed, align: LogStringAlignment = .none, privacy: LogPrivacy = .private) {
>                          ^
> [12/13] Compiling LoggingTests Test+Public.swift
> error: fatalError
> 

```
PR to fix these build errors to be provided shortly.

### PR DESCRIPTION
**Pull request by GeekAndDad**
Interchangable use of CGFloat and Double isn't supported until Swift 5.5:

https://github.com/apple/swift-evolution/blob/main/proposals/0307-allow-interchangeable-use-of-double-cgfloat-types.md

Addes #if swift(<5.5) conditional to allow compiling in older Swift versions.

Note: Only ran the tests on macOS 11.5.2.
All Test+Float tests pass in Swift 5.4.2 with this change, and it compiles in both 5.4.2 and 5.5, but there's a test assertion failure in Swift 5.5 (release version with Xcode 13.0).  That's a separate issue.

Fix for issue #1 

Added conditional test for swift version and construct a `Double` manually on swift compiler versions less than 5.5.

Note: This PR doesn’t address project’s other failing tests in Test+Private.swift in Swift 5.5 and 5.4.2 even with this fix. Those filed as #2

### CODE REVIEW

File: Tests/LoggingTests/Test+Floats.swift [hunk 1]
```diff
@@ -19,7 +19,11 @@ final class FloatTests: XCTestCase {
         logger.debug("\(max, privacy: .public)")
         XCTAssertEqual(logging.recorder.message, "\(CGFloat.greatestFiniteMagnitude)")
 
+        #if swift(<5.5)
+        logger.debug("\(Float(value), format: .fixed(precision: 2), privacy: .public)")
```
Comment (shaps80) [inline Tests/LoggingTests/Test+Floats.swift:23]: Hmm this satisfies the compiler but not the test. We shouldn't be correcting the test but rather the code this is testing. I'll review the actual problem and see what's going on. I'll leave this PR open for now.

Comment (haikusw) [reply Tests/LoggingTests/Test+Floats.swift:23]: Yep. Smallest change path.

I did it the other way but that involved more code and then ran into the precision issue.
I'll submit a separate PR with that version since it is the more complete fix.

Comment (GeekAndDad) [reply Tests/LoggingTests/Test+Floats.swift:23]: Yep. Smallest change path.

I did it the other way but that involved more code and then ran into the precision issue.
I'll submit a separate PR with that version since it is the more complete fix.
